---
#############################################
#  Active-Window Reconstruction Parameters  #
#############################################
active_window:
  frame_data_buffer:
    max_buffer_size: 300
    store_every_n_frames: 1
  object_extractor:
    min_object_allocation_confidence: 0.5
    min_object_volume: 0.0  # m^3
    max_object_volume: 8.0  # m^3
    only_extract_reconstructed_objects: true
    min_object_reconstruction_confidence: 0.5
    min_object_reconstruction_observations: 3
    object_reconstruction_resolution: -0.03  # Positive: voxel size in meters. Negative: fraction of the extent. 0: Skip. (-0.02)
  object_detector:
    min_cluster_size: 20  # pixels
    max_cluster_size: 50000  # pixels
  tracker:
    semantic_association: assign_track   # 'assign_cluster', 'assign_track'
    min_semantic_iou: 0.4
    min_cosine_sim: 0.7
    min_cross_iou: 0.1
    temporal_window: 5.0
    min_num_observations: 5
########################
#  Backend Parameters  #
########################
backend:
  update_functors:
    objects:
      min_segment_score: 0.0
      selector:
        max_delta: 1.0e-5
        score_threshold: 0.23
        top_k: 2
        cumulative: true
        null_task_preprune: true
