---
# code to convert topformer model to onnx: https://github.com/hustvl/TopFormer/blob/main/tools/convert2onnx.py
# TopFormer-S_512x512_2x8_160k.yaml
segmenter:
  model:
    color:
      mean: [0.485, 0.456, 0.406]
      stddev: [0.229, 0.224, 0.225]
